---
title: "Syllabus"
---

**Instructors:** Jason Bryer, Ph.D. and Angela Lui, Ph.D.  
**Class Meetup:** Wednesday 8:00pm to 9:00pm  
**Office Hours:** By appointment  
**Email:** <a href="mailto:jason.bryer@cuny.edu">jason.bryer@cuny.edu</a>, <a href="mailto:angela.lui@cuny.edu">angela.lui@cuny.edu</a>    


### Course Description

This course covers basic techniques in probability and statistics that are important in the field of data analytics. Discrete probability models, sampling from infinite and finite populations, statistical distributions, basic Bayesian statistics, and non-parametric statistical techniques for categorical data are covered in this course. Each of these statistical concepts will be applied in a variety of real-world scenarios through the use of case studies and customized data sets.


### Course Learning Outcomes:

By then end of the course, students should be able to:

* Understand the foundations of probability theory and perform basic probability calculations.
* Build basic stochastic models for commonly encountered business problems.
* Model situations involving uncertainty using appropriate probability distributions and conditional techniques.
* Explore and summarize data using descriptive statistics.
* Test hypotheses using classical and modern computational techniques.
* Construct estimators and calculate intervals using classical and modern computational techniques.
* Perform basic Bayesian statistical techniques for estimation and testing hypotheses.

### Program Learning Outcomes addressed by the course:

* Business Understanding:  Learn when probabilistic techniques apply to certain categories of business problems, discuss the sorts of solutions that are possible, and understand the limitations of these techniques.
* Foundational Math Skills: Explore and analyze data, build probabilistic and statistical models, construct estimators, and test hypotheses.
* Predictive Modeling:  Learn foundational techniques that underlie predictive modeling algorithms, such as Naïve Bayes.
* Presentation:  Complete and submit collaborative assignments using techniques from the course.

### How is this course relevant for data analytics professionals?

Probabilistic techniques are the foundation of many data science applications from data exploration and visualization to outlier analysis, stochastic modeling, and data mining algorithms. This course will ensure that students have a strong understanding of these foundations.

### Grading

* [Participation](/assignments/participation) (10%)
	* [DAACS](/assignments/daacs)
	* [One Minute Papers](/assignments/participation)
* [Labs](/assignments/labs) (35%)
* [Data Project](/assignments/project) (30%)
* [Exams](/assignments/exams/)
	* Midterm (10%)
	* Final exam (15%)

#### Grade Distribution

Quality of Performance                     | Letter Grade | Range %   | GPA  |
-------------------------------------------|:------------:|:---------:|:----:|
Excellent - work is of exceptional quality |      A       | 93 - 100  |  4   |
Excellent                                  |      A-      | 90 - 92.9 | 3.7  |
Good - work is above average               |      B+      | 87 - 89.9 | 3.3  |
Satisfactory                               |      B       | 83 - 86.9 |  3   |
Below Average                              |      B-      | 80 - 82.9 | 2.7  |
Poor                                       |      C+      | 77 - 79.9 | 2.3  |
Poor                                       |      C       | 70 - 76.9 |  2   |
Failure                                    |      F       |   < 70    |  0   |

### How This Course Works

This course is conducted entirely online. Each week, you will have various resources made available, including weekly readings from the textbooks and occasionally additional readings provided by the instructor. Most weeks will have homework assignments and labs to be submitted (although some chapters will take more than one week, see the [schedule](/course-overview/schedule/) for details). There will also be a presentation required and a forum post introduction required. You are expected to complete all assignments by their due dates.

**You are expected to attend or watch every Meetup.** We highly recommend attending the Meetups live if possible but understand that may not be possible for everyone. Recordings will be made available by the next morning on the [Meetups page](/course-overview/meetups/). In addition to highlighting key concepts from each learning module, some topics will be discussed that are not in the textbook. Moreover, we regularly make announcements in the Meetups that will be important to being successful in this course. At the end of each Meetup there will be a short reflective exercise. These will contribute to your participation grade.

The culmination of the course will be the presentation of the analysis of a dataset of your choosing. There will be a number of time slots available to present. You will be **required to attend one presentation session**, during which you will present your analysis and provide peer feedback for other students in that timeslot. See the [project](/assignments/project/) for more information.

### Accessibility and Accommodations

The CUNY School of Professional Studies is firmly committed to making higher education accessible to students with disabilities by removing architectural barriers and providing programs and support services necessary for them to benefit from the instruction and resources of the University. Early planning is essential for many of the resources and accommodations provided. Please see: [http://sps.cuny.edu/student_services/disabilityservices.html](http://sps.cuny.edu/student_services/disabilityservices.html)

### Online Etiquette and Anti-Harassment Policy

The University strictly prohibits the use of University online resources or facilities, including Blackboard, for the purpose of harassment of any individual or for the posting of any material that is scandalous, libelous, offensive or otherwise against the University’s policies.  Please see: [http://media.sps.cuny.edu/filestore/8/4/9_d018dae29d76f89/849_3c7d075b32c268e.pdf](http://media.sps.cuny.edu/filestore/8/4/9_d018dae29d76f89/849_3c7d075b32c268e.pdf)

### Academic Integrity

Academic dishonesty is unacceptable and will not be tolerated. Cheating, forgery, plagiarism and collusion in dishonest acts undermine the educational mission of the City University of New York and the students' personal and intellectual growth. Please see: [http://media.sps.cuny.edu/filestore/8/3/9_dea303d5822ab91/839_1753cee9c9d90e9.pdf](http://media.sps.cuny.edu/filestore/8/3/9_dea303d5822ab91/839_1753cee9c9d90e9.pdf)

### Student Support Services

If you need any additional help, please visit Student Support Services: 
[http://sps.cuny.edu/student_resources/](http://sps.cuny.edu/student_resources/)
